CREATE DATABASE "INTEGRACAO";
\c INTEGRACAO;

CREATE SEQUENCE SEQ_LIVROS INCREMENT 1 START 1;
CREATE TABLE LIVROS
(
  ID int PRIMARY KEY DEFAULT NextVal('SEQ_LIVROS'),
  LIVRO varchar(64) NOT NULL,
  AUTOR varchar(32) NOT NULL,
  EDITORA varchar(16) NOT NULL
);